- jquery.fullPage.js
We're getting a type error "Cannot read property 'top' of undefined" - I'm adding a condition to check if an element exists before calling position().  Note, this is already done above within the method [here](https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L99).
Error occurs when destroy('all') is called.
> avoid TypeError

- jquery.fullPage.js
When I updated fullPage.js I noticed that the body class had changed to `fp-viewing0` instead of `fp-viewing-0` (this started happening in rev 9702c05). Added the dash back in.
Also updated the regexp that cleans the body classes to use the constant `VIEWING_PREFIX`.
Thanks for this awesome script! Keep up the good work :+1:
> Fix setBodyClass method

- jquery.fullPage.js
Only apply top and bottom padding values so not to overwrite existing left/right padding values of the section element.
> Explicit padding-top/bottom inline styles

- jquery.fullPage.js
... in Firefox.  Code defensively against this.
This fix tested in Firefox & Chrome, but not IE.
> window.event can actually refer to an HTML element

- examples/backgroundVideo.html
Only omission of `controls` attribute will hide background video controls.
`controls="false"` does nothing.
> fixes issue where background video controls were visible

- jquery.fullPage.js
This is a first shot at addressing https://github.com/alvarotrigo/fullPage.js/issues/1337.
> lazyLoad: per slide

- jquery.fullPage.js
`this` is the `window` object currently, although the documentation
states that it should be the plugin container.
> Pass down container to call of `afterRender`

- jquery.fullPage.js
- tests/functions.js
This PR makes fullPage.js clean up the `<html/>` and `<body/>` inline styles and adds a test that ensures this is happening (run it on the old version and see that it fails). The test could probably also check the container, but I'm unsure what that is in the test file (I think `$('#fullpage')`)
Your package.json doesn't include a build script, so I did not update the .min.js file.
> [Patch] [Test] Clean up html and body tags on destroy

- README.md
- jquery.fullPage.js
- pure javascript (Alpha)/javascript.fullPage.js
Hey,
when using fitToSection fullPage.js currently uses a hardcoded 1000ms-delay.
This PR introduces a simple option for said delay.
The changes are not yet minified as I was not sure what exactly you are using for that :/
> added option `fitToSectionDelay`

- jquery.fullPage.js
I used numbers in `data-anchor` and got an error. The `text` variable was an integer which does not have the `replace` method. I fixed it with forcing the variable to be a string.
You want it in another branch, or in another way? :)
> Force string for anchor names

- jquery.fullPage.js
This update adds a new option called 'scrollOverflowHandler'
which consolidates all code related to scrollOverflow and
allows it to be swapped out with different functionality.
By default, it will use the existing jquery.slimScroll handling
of scroll overflow.
This should make it easier for users to either customize the
slimScroll handling or replace it with other code just as wrapping
content in a div with overflow: scroll or utilizing iscroll.js
as requested in issues #506, #612 and others.
This pull request is a re-opening of #1498 against the new "dev" branch.
> Moves scrollOverflow code to separate handler object

- jquery.fullPage.js
Adding prefixes to requestAnimationFrame extend support to older browser.
In my case i tested in FF20.
> Add prefix for older browser versions

- README.md
- jquery.fullPage.js
Thus, we can easily apply CSS rules to elements outside the plugin container.
Can be particularly useful for hiding static positioned elements such as vertical navigation arrows (#814) which cannot be easily included in the plugin container because of the transform property.
Furthermore, `$(SECTION_NAV_SEL).hide();` and `$(SECTION_NAV_SEL).show();` in `setResponsive()` function could be replaced with a simple CSS rule:
`
.fp-responsive #fp-nav {
display: none;
}
`
> Move fp-responsive class to the body tag

- jquery.fullPage.js
Fixed: Scroll failing when first section be set to auto height
After scroll down to other section, can not scrolling up to first section,
first section will not be display again .
https://github.com/alvarotrigo/fullPage.js/pull/1679
> Fixed: Scroll failing when first section be set to auto height

- jquery.fullPage.js
Under normal scroll (`autoScrolling: false`), when a section is longer than the window height, the active flag in navigation can be wrong. This PR fixes this issue.
The current logic (in the base fork) calculates the difference between the `section.offsetTop` and `$window.scrollTop()` for each section and pick the one with the smallest diff as active. However, this can be wrong. For example, suppose there are two sections A and B, where section A is much longer than the window height. Consider the case when you have *just* scrolled B entering the viewport. At this point, section B occupies very little area of the window, whereas section A still dominates. However, `diff(A.offsetTop, window.ScrollTop) < diff(B.offsetTop , window.ScrollTop)` as A is very long and the top of B is much closer …
> Fix the wrong active section flag under normal scroll

- jquery.fullPage.js
on load will not be called if it's binded after onload event,
and jquery ready function will always be called whether document is ready.
(if document has been ready, it will be called immediately)
Found this problem cause I use fullpage in ajax callback (when onload has passed)
> Fix: scrollToAnchor may not be called

- bower.json
My Gulp process with asset-builder can't get the correct file because of typo
> Typo on main file name

- jquery.fullPage.js
if the value of window.location.hash is Chinese, auto scroll will fail on safari
> fix bug for safari when anchor is unicode 

- README.md
Port library for a new modern [Angular 2](http://angular.io) framework.
For additional details visit project github page: [https://github.com/meiblorn/ng2-fullpage](https://github.com/meiblorn/ng2-fullpage) or [demo](meiblorn.github.io/ng2-fullpage)
> fullpage.js Angular 2 directive

- jquery.fullPage.js
This was tripping me up for awhile. After destroying fullPage the fp-responsive class remained on the body and when I re-initialized fullPage it wouldn't go into responsive mode. Removing this class from the body when destroying fullPage fixed this problem.
Great plugin btw! Thank you!
> remove class RESPONSIVE from $body in destroyStructure function

- jquery.fullPage.js
getFullpageData sets getTransforms option twice, causing issues in IE
> removes redundant getTransforms

- jquery.fullPage.js
Removing touch events when fullpage is destroyed.
Before only click events were being removed on destroy(), which caused multiple touch events to be fired when reinitializing Fullpage.
> Removing touch events when fullpage is destroyed

- .gitignore
- jquery.fullPage.js
continuousHorizontal was set to `true` resulting in a console warning.
Updated to `continuousHorizontal: false`.
Also made the warning clearer by showing what extension is requested.
> Bugfix: continuousHorizontal should default to false

- jquery.fullPage.js
I got error since I didn't have jQuery globally defined. All other places in the code `$` is used as well, not sure why `jQuery` was used here
> Use $ instead of jQuery

- jquery.fullPage.js
Hi Alvaro,
I noticed that the `onLeave` callback was firing too soon, which caused my implementation to break when pressing down (next slide) multiple times. The callback would fire, even though the previous animation was not completed yet.
So I added this check in the `keydownHandler()` function. It's not in the same if-statement as the others, because this would sometimes cause a normal "down" event to fire, scrolling the page one tick, showing a piece of the next section, and then centering on the proper section again.
Hope you find this helpful.
Regards,
Jorn
> Prevent keypresses to fire prematurely

- jquery.fullPage.js
Addressing issue #2664
- *Library version*: 2.9.4.
- *Issue*: 
- iframes are not recognized correctly as "normalScrollElements" during touch events, as they don't propagate touch events within them.
- *Proposed solution*: 
- add explicit `touchstart` and `touchend` listeners to "normalScrollElements" 
- disable general scrolling on `touchstart` event (instead of disabling only mouse wheel scrolling)
- re-enable general scrolling on `touchend` event
- *Proposed changes*:
- edit fil jquery.fullPage.js [lines 604 to 620]
> Re-submit of pull request #2665

- jquery.fullPage.js
Addressing issue #2664
- *Library version*: 2.9.4.
- *Issue*: 
- iframes are not recognized correctly as "normalScrollElements" during touch events, as they don't propagate touch events within them.
- *Proposed solution*: 
- add explicit `touchstart` and `touchend` listeners to "normalScrollElements" 
- disable general scrolling on `touchstart` event (instead of disabling only mouse wheel scrolling)
- re-enable general scrolling on `touchend` event
- *Proposed changes*:
- edit file jquery.fullPage.js [lines 604 to 620]
> Re-re-submit of pull request #2665

- README.md
I had a long-standing issue where `scrollOverflow: true` was not doing anything. After a lot of time debugging, I eventually found that loading it after jQuery solved the issue. I think that it is very important for other people to know this so that they don't have to go through the pointless journey I went through.
I feel really stupid now
> Tell people to load the scrollOverflow script after jQuery

- vendors/scrolloverflow.js
Move getPaddings func to upper scope since it is not available in iscrollHandler object:
https://github.com/alvarotrigo/fullPage.js/blob/c0019fbc33ee54c82a593d91fa556b572352aa32/vendors/scrolloverflow.js#L2736
> Move getPaddings to upper scope

- jquery.fullPage.js
This is made necessary as the fix for  #1237, by adding the `onTab` function is not reverted on destroying fullpage.js plugin. Consequently, this was breaking tab functionality when the plugin is no longer active.
> Remove keydown handler on destroy

- jquery.fullPage.js
1. Complementing #3124, unbinding the keyup handler as well to revert to the original state on destroying fullpage.js.
2. Version bump to 2.9.7
> Remove keyup handler on destroy

- src/fullpage.js
If you import fullpage.js into a module without a jQuery dependency and bundled with webpack.
When using the bundle in a page that has jQuery as a global, it will expect fullpage to exist as a global which can cause an error.
By adding window.jQuery && window.fullpage to the conditional it will prevent the adapter from loading unless fullpage is a global.
> Prevent jQuery adapter from loading when fullpage is not global

- src/fullpage.js
Checks for undefined before calling focus() on an element
I'm facing a problem in my React app that uses fullpage.js. Whenever I press the Tab key, the keydown handler inside fullPage fails and prevents my own keydown handlers to work. In this pull request, I added a simple check that prevents calling `.focus()` on `undefined`.
> Add safeguards in onTab

- src/fullpage.js
Added an extra option to display a warning the user that autoScrolling and scrollOverflow are exclusive.
> Bugfix #3403: autoscrolling and scrolloverflow are exclusive.

- lang/chinese/README.md
The Chinese quote mark doesn't work in Markdown as a ending quote mark. Replacing it.
> chinese/README.md: Fix markdown link

- src/fullpage.js
- vendors/scrolloverflow.js
There are two bugs with the same root cause that current PR fix:
Assuming you have elements inside your section with attached event listeners (e.g. in case of using angular it can be ng-bind).
1) After initializing FullPage your section content will be wrapped by additional HTML markup.
If you call "destroy('all')" this markup will be removed and content returned to original state. But actually all DOM elements will be recreated, because innerHTML/outerHTML properties are used for unwrapping.
Hence all listeners won't work after that. 
2) Assuming you are using scrolloverflow with FullPage. Your section content will be wrapped by scrolloverflow markup. Now you resize your window to the size when scrollbar should be hidden. As result scrolloverflow markup will be removed. The same method …
> Bugfix: loss attached events on unwrapping

- src/fullpage.js
1- Make sure to commit it to the 'dev' branch!
In applications that generate and destroy templates dynamically, as like MeteorJS,
templates are destroyed by template engine. 
When fullpage_api.destroy('all') is called, current templates are already removed. 
it makes undefined Object error.
To avoid this, I added just conditional statement $(WRAPPER_SEL)[0] is still exists or not.
(I found this issue when I test laptop device that has touch screen )
Thank you!
> Add conditional statement before remove eventListener

- src/fullpage.js
- tests/index.html
- tests/unit/menu.js
**Description**
In the change from v2.* to v3.* there was a regression in the code. In v2.* when providing a selector for the menu options you could provide a class selector and it would target all matched elements, in v3.* it will only target the first matched element.
**Link to isolated reproduction with no external CSS / JS**
Functionality in v2.6.6
Functionality in v3.0.4
**This PR Contains**
Passing QUnit tests describing the missing functionality
Updates to `styleMenu` and `activateMenuElement` functions to make them deal with multiple menus rather than just grabbing the first matched element from the given selector
> Fixes #3613

- README.md
In reference to alvarotrigo#3626 - clarifying that the first section will have an index of 1 but the first slide (in any section) will have the index of 0.
> Clarifies section index starts at 1 and slide at 0

- src/fullpage.js
See original commit for more detail.
This adds an eventHandler for focus events to set isWindowFocused to true, otherwise this is left on false forever after a single blur event.
> Reassigning value for isWindowFocused on focus event

- src/fullpage.css
- src/fullpage.js
#3925 Vertical Centering of #fp-nav was achieved by mixing css margin-top
and Javascript which applied directly to the element resulting in
having to use too much css overrides and !important when moving the
navigation with callbacks or styling the vertical navigation menu
> #3925 Vertical Center #fp-nav Using 2D Transform

- vendors/scrolloverflow.js
This is a fix for the issue #3931, that appears when **normalScrollElements** option is added and mouse cursor leaves from a browser window.
When the mouse cursor left the viewport, the **scrollable** variable was not assigned a value, because the **target** parameter, in this case, is null. So, I just added a check for the **target** parameter value in **2409** line.
> Fix for #3931 (normalScrollElements option)

- examples/navigation-vertical.html
Hi! Quick PR to swap 'throw' with 'through' for the description of vertical navigation:
Including 'the' before 'sections' also isn't necessary, but I'd consider that a more stylistic choice.
> Fix typo: throw->through
