alvarotrigo/fullPage.js

jquery.fullPage.js
Just a small update.. 
Cheers! :)
=> Update Copyrights Header

jquery.fullPage.js
Related discussion:
https://github.com/alvarotrigo/fullPage.js/issues/1148
=> Use rounded values for horizontal scroll transformations

jquery.fullPage.js, package.json
was corresponding to UMD. please npm publish
=> corresponding to umd

pure javascript (Alpha)/javascript.fullPage.js
Reverts alvarotrigo/fullPage.js#1201
=> Revert "When use 'slidesNavigation: true', it has error."

jquery.fullPage.js
Hello,
I had a need for a callback in my project that could be triggered before a slide moves so I could prevent the slide from moving under certain conditions. Feel free to use this minor change for the fullPage.js project as you see fit.
Cheers
=> Added a callback that could be triggered before a slide move.

jquery.fullPage.js
Reverts alvarotrigo/fullPage.js#1194
=> Revert "Added a callback that could be triggered before a slide move."

jquery.fullPage.js, tests/functions.js
Noticed that fullPage.js was not cleaning up the classes on `<html/>` and `<body/>`, so added a test and then fixed the bug.
I *think* I've got fullPage.js cleaning everything up now. :)
=> [Patch] [Test] Clean up more things

jquery.fullPage.js
Fix the potential problem with old jQuery and newer jQuery with Migrate plugin.
i don't want to write specific about this problem because of it's a sort of security issue.
see https://github.com/jquery/jquery-migrate/issues/36 and https://bugs.jquery.com/ticket/9521
=> fix potential problem

README.md
=> Mergin Dev branch

jquery.fullPage.js
Allows use of any kind of selector as options.sectionSelector
=> using $.filter() in setOptionsFromDOM()

README.md
=> Fix link to scrolloverflow.min.js

README.md
- Fixed problemin IE thanks to @ironprogrammer  #2203
=> Fixed problem in IE

jquery.fullPage.js
Refer to https://github.com/alvarotrigo/fullPage.js/pull/2176
=> Changes CommonJS detection logic

package.json
Just remove an extra white space between the words
=> Remove extra white space

jquery.fullPage.js
=> Fixed typo

jquery.fullPage.js
=> fixed typo / 2

README.md, jquery.fullPage.js
Reverts alvarotrigo/fullPage.js#2420
=> Revert "Offset top option"

package.json
- Updating packages file version
=> - Updating packages version

examples/parallax.html
=> - Adding parallax example

README.md, README_SPANISH.md
- Documentation aesthetics changes
=> - Documentation aesthetics changes

jquery.fullPage.js
Reverts alvarotrigo/fullPage.js#2683
=> Revert "Re-submit of pull request #2665"

README.md, README_SPANISH.md
Reverts alvarotrigo/fullPage.js#2661
=> Revert "- Aesthetics changes"

lang/spanish/README.md
And some minor fixes (proposal)
=> Typos found

lang/korean/how-to-activate-fullpage-extension.md, lang/spanish/how-to-activate-fullpage-extension.md
- Documentation: improving Korean & Spanish docs
=> - Documentation: improving Korean & Spanish docs

lang/korean/README.md
=> Missing backtick(`) after section

jquery.fullPage.js
=> Wrong version

src/fullpage.js
1- Make sure to commit it to the `dev` branch! **v**
2- Read https://github.com/alvarotrigo/fullPage.js/wiki/Contributing-to-fullpage.js **v**
=> Added showError to fp_utils as its required by the jQuery Adapter

src/fullpage.js
setAllowScrolling: false does not work with scrollBar:true.
Added else if update to ensure scrolling stopped when appropriate.
=> Bug Fix: #3392

src/fullpage.js
Reverts alvarotrigo/fullPage.js#3426
=> Revert "workaround for issue #44. "

README.md, lang/chinese/README.md, lang/korean/README.md, lang/russian/README.md, lang/spanish/README.md
=> Documentation: fixed typo

lang/chinese/README.md
Beautified chinese README.md, added the space between chinese and english, improved chinese reading experience.
=> update: Chinese README.md

lang/chinese/README.md
Improved further formatting issues
=> Improved further formatting issues

README.md
=> Remove redundancy and hedging from README

README.md, lang/korean/README.md
=> - Documentation: fixed typo

examples/angular-fullpage.html, examples/react-fullpage.html
* Done
Just updating the title, not sure if it helps but you can merge if it is.
=> Rename angular & react document title in examples

src/fullpage.js
Fixes a small typo in fullpage.js
Replaces `or` with `of` in fullpage.js on the line 3600
=> Fixes a small typo in fullpage.js

lang/french/README.md
I finished the whole job. I'll give you time to go over the work.
=> French documenatation reviewed

lang/french/README.md, lang/french/how-to-activate-fullpage-extension.md, lang/french/parallax-extension.md
- Documentation: improved french docs links #3856
=> - Documentation: improved french docs links #3856

README.md, lang/chinese/README.md, lang/french/README.md, lang/korean/README.md, lang/russian/README.md, lang/spanish/README.md
- Documentation: link to elementor + small fixes in french docs
=> - Documentation: link to elementor + small fixes in french docs

README.md, lang/chinese/README.md, lang/french/README.md, lang/korean/README.md, lang/russian/README.md, lang/spanish/README.md
Documentation: removing old links
=> Documentation: removing old links

README.md, lang/chinese/README.md, lang/french/README.md, lang/korean/README.md, lang/russian/README.md, lang/spanish/README.md
- Documentation: fixed syntax errors
=> - Documentation: fixed syntax errors

README.md
- Documentation: adding dropEffectOptions in english
=> - Documentation: adding dropEffectOptions in english

README.md
=> - Docs: updating version

lang/french/README.md, lang/korean/README.md, lang/russian/README.md, lang/spanish/README.md
=> - Docs: updating compatible  img

README.md, lang/chinese/README.md, lang/french/README.md, lang/korean/README.md, lang/russian/README.md, lang/spanish/README.md
=> Docs improvements

package.json
- Build: remove unused dependency gulp-sass (fix #4694)
=> Remove unused gulp-sass dependency
